### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ydong6**

### CODE REVIEW

**Comment by brantfaircloth** [comment]
This is still not correct.  It contains the following files:

```
answers/assignment1.py
answers/assignment2.py
answers/assignment3.py
answers/assignment4.py
answers/assignment5.py
```
You should not submit these files, only the files you have in `answers/ydong6/`.  Most folks from class should be able to help you if you still are not sure what I mean.

**Comment by ydong6** [comment]
Hello Dr. Faricloth,
These files are not in the answer folder on my computer. And I have deleted those files before the resubmit, but they show up again after I submit. So I went online to the github, and deleted from the answers folder by manual. Is this OK now?
Thanks,
Yuankai Dong

**Comment by brantfaircloth** [comment]
ok - now resubmit the pull request and you should be good.

-b

**Comment by ydong6** [comment]
I resubmitted, does it work now?

**Pull request closed without merging**
